### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [TatakAdi/Project1-PMB-Tatak-Adi-11221073#1]
### Halo Adi,

Ada beberapa revisi nih buat websitenya nih:

1. Untuk elemen `main`, bisa dikeluarin `aside` dari `div id="content"`:
```html
<main>
 <div id=content>
  <section>Konten Deskripsi Website</section>
  <section>Konten-Konten Artikel</section>
  <section>Form Kontak Saya</section>
 </div>
 <aside>"Isi Konten Aside"</div>
</main>
```

Untuk yang lain udah oke tetapi ada hal optional yang perlu dilakukan seperti
1. Membuat file CSS, lalu menghapus elemen `style` dan memindahkan isinya kedalam file CSS
2. koreksi atribut dibawah, menghapus koma karena tidak perlu koma yah, cukup spasi untuk pemisahan:
![image](https://github.com/TatakAdi/Project1-PMB-Tatak-Adi-11221073/assets/73971391/ba7458fe-ad13-4f15-90bc-1c83ce990ebe)

Itu aja dari aku, bisa direvisi baru kuapprove. Jika sudah direvisi silahkan komen dibawah dan jangan lupa untuk mengupload ulang di repo yang sama ini yah. Terimakasih

**Comment by not-xygen** [comment]
### Halo Adi

Kode struktur masih kurang tepat:
![image](https://github.com/TatakAdi/Project1-PMB-Tatak-Adi-11221073/assets/73971391/5a8e1ec7-d669-4b6a-b9d8-4d6bc0da5af8)
Keliatan ya, kalau `main` masih dibungkus `div` dan footer karena sudah ada pembungkus `footer` tidak perlu `div id="footer"` lagi ya, lalu articlemu bisa dimasukin ke section. Bisa diperbaiki mengikuti contoh struktur dibawah yah:
```html
<header>...</header>
<main>
 <div id="content">
  <section id="article">...</section
  <section id="article">
   <article id="">...</article>
   <article id="">...</article>
   ...
  </section>
  <section id="form">...</section>
  ...
 </div>
 <aside>...</div>
</main>
<footer>...</footer>
```

Yang lain udah oke, bisa direvisi lalu upload ulang di repository ini juga, lalu komen dibawah jika sudah upload ulang ya. Terimakasih

**Comment by TatakAdi** [comment]
Sudah direvisi lagi kak 👍

**Comment by not-xygen** [comment]
### Malam

Oke submission approved!!, Goodluck di CSS!
